name: mgst-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  # Runtime dependencies
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.1.0
  - tqdm>=4.64.0
  - click>=8.0.0
  - pydantic>=1.10.0
  - requests>=2.28.0
  - setuptools>=61.0
  - pip
  # Development dependencies
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - flake8>=5.0.0
  - mypy>=0.991
  - pre-commit>=2.20.0
  - pip:
    - -e .
