name: mgst
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.1.0
  - tqdm>=4.64.0
  - click>=8.0.0
  - pydantic>=1.10.0
  - pip
  - pip:
    - -e .
